# Grouping operations and summary statistics

## Aggregate summary statistics

```{r, message=FALSE, warning=FALSE}
usa_counties_total_rural<-get_decennial(geography = "county", 
                                        variables = c("P001001", "P002005"),
                                        output="wide",
                                        year = 2010) %>% 
                          rename(total_population=P001001, rural_population=P002005)

```

```{r, eval=F}
View(usa_counties_total_rural)
```

```{r, echo=FALSE}
kable(head(usa_counties_total_rural, n=6))
```


```{r}
usa_counties_summary<-usa_counties_total_rural %>% 
                          select(total_population, rural_population) %>% 
                          describe() %>% 
                          as_tibble(rownames="variable")
```


```{r}
usa_counties_summary
```

```{r, echo=FALSE}
kable(usa_counties_summary)
```

```{r}
usa_counties_summary<-usa_counties_summary %>% 
                        select(variable, n, mean, sd, median, , min, max, range)
```

```{r, echo=FALSE}
kable(usa_counties_summary)
```

## Summary statistics by group

Create separate state field 
```{r}
usa_counties_states_total_rural<-usa_counties_total_rural %>% 
                                    separate(NAME, into=c("County", "State"), sep=", ")
```

```{r, echo=FALSE}
kable(head(usa_counties_states_total_rural, n=6))
```


Summary statistics by group

```{r}
group_summary<-usa_counties_states_total_rural %>% 
                  group_by(State) %>% 
                  summarise(number_counties=n(),
                            mean_county_pop=mean(total_population),
                            median_county_pop=median(total_population),
                            mean_county_rural_pop=mean(rural_population),
                            median_rural_county_population=median(rural_population))
```

```{r, echo=FALSE}
kable(group_summary) %>% kable_styling(font_size = 10)
```







